#!/system/bin/sh
# chmod-on-write.sh <name> <addr> <user> <pass> <remote-root> <EVENTS> <FILE> [<DIRFILE>]
# Called by a per-remote wrapper generated by auto-chmod-watch.sh, itself
# invoked by inotifyd on write events under the remote's local mountpoint.
#
# Never chmods by filename pattern: only actual shebang scripts or ELF
# binaries get +x, so unrelated files (images, .git internals, keys, sync
# tool databases, etc.) that happen to be new are left alone.

MODDIR="${0%/*}/.."
SSHRUN="$MODDIR/system/vendor/bin/sshrun"

NAME="$1"; ADDR="$2"; USER="$3"; PASS="$4"; ROOT="$5"; EVENTS="$6"; WATCHED_DIR="$7"; DIRFILE="$8"

# Only a direct-child write event carries a DIRFILE; ignore anything else
# (e.g. events on the watched directory itself).
[ -z "$DIRFILE" ] && exit 0

LOCAL_PATH="$WATCHED_DIR/$DIRFILE"
REMOTE_PATH="$ROOT/$DIRFILE"

# File may have already been removed/renamed by the time we get to check it.
[ -f "$LOCAL_PATH" ] || exit 0

MAGIC=$(head -c4 "$LOCAL_PATH" 2>/dev/null | od -An -tx1 | tr -d ' \n')
SHEBANG=$(head -c2 "$LOCAL_PATH" 2>/dev/null)

if [ "$MAGIC" = "7f454c46" ]; then
  "$SSHRUN" "$ADDR" "$USER" "$PASS" "chmod +x '$REMOTE_PATH'" \
    >> "$MODDIR/logs/auto-chmod.log" 2>&1
  echo "$(date '+%F %T') ELF chmod+x: $NAME:$REMOTE_PATH" >> "$MODDIR/logs/auto-chmod.log"
elif [ "$SHEBANG" = "#!" ]; then
  "$SSHRUN" "$ADDR" "$USER" "$PASS" "chmod +x '$REMOTE_PATH'" \
    >> "$MODDIR/logs/auto-chmod.log" 2>&1
  echo "$(date '+%F %T') script chmod+x: $NAME:$REMOTE_PATH" >> "$MODDIR/logs/auto-chmod.log"
fi
